source 'https://rubygems.org'

gem 'rails', '3.2.8'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'twitter-bootstrap-rails'
  gem 'uglifier', '>= 1.0.3'
end

group :test do
  gem 'shoulda-context'
  gem 'shoulda-matchers'
  gem 'factory_girl'
end

gem 'haml'
gem 'mongoid'
gem 'jquery-rails'
gem 'mongoid'
gem 'unicorn'

# gem 'debugger'
